package mobi.xdsp.tracking.dto.enums;

import com.google.common.collect.Maps;

import java.util.Map;

public class IABcats {
    public static Map<String, String> CATS = Maps.newHashMap();
    static {
        CATS.put("IAB1","Arts & Entertainment-艺术与娱乐");
        CATS.put("IAB1-1","Books & Literature-书籍与文学");
        CATS.put("IAB1-2","Celebrity Fan/Gossip-名人粉丝/八卦");
        CATS.put("IAB1-3","Fine Art-美术");
        CATS.put("IAB1-4","Humor-幽默");
        CATS.put("IAB1-5","Movies-电影");
        CATS.put("IAB1-6","Music-音乐");
        CATS.put("IAB1-7","Television-电视");
        CATS.put("IAB2","Automotive-汽车");
        CATS.put("IAB2-1","Auto Parts-汽车零件");
        CATS.put("IAB2-2","Auto Repair-自动修理");
        CATS.put("IAB2-3","Buying/Selling Cars-购买/出售汽车");
        CATS.put("IAB2-4","Car Culture-汽车文化");
        CATS.put("IAB2-5","Certified Pre-Owned-认证二手车");
        CATS.put("IAB2-6","Convertible-可兑换");
        CATS.put("IAB2-7","Coupe-双门跑车");
        CATS.put("IAB2-8","Crossover-交叉");
        CATS.put("IAB2-9","Diesel-柴油机");
        CATS.put("IAB2-10","Electric Vehicle-电动汽车");
        CATS.put("IAB2-11","Hatchback-两厢");
        CATS.put("IAB2-12","Hybrid-混合动力");
        CATS.put("IAB2-13","Luxury-豪华");
        CATS.put("IAB2-14","Minivan-面包车");
        CATS.put("IAB2-15","Motorcycles-摩托车");
        CATS.put("IAB2-16","Off-Road Vehicles-越野车");
        CATS.put("IAB2-17","Performance Vehicles-表现车辆");
        CATS.put("IAB2-18","Pickup-拾起");
        CATS.put("IAB2-19","Road-Side Assistance-道路救援");
        CATS.put("IAB2-20","Sedan-四门轿车");
        CATS.put("IAB2-21","Trucks & Accessories-卡车及配件");
        CATS.put("IAB2-22","Vintage Cars-老式汽车");
        CATS.put("IAB2-23","Wagon-车皮");
        CATS.put("IAB3","Business-商业");
        CATS.put("IAB3-1","Advertising-广告");
        CATS.put("IAB3-2","Agriculture-农业");
        CATS.put("IAB3-3","Biotech/Biomedical-生物技术/生物医学");
        CATS.put("IAB3-4","Business Software-商业软件");
        CATS.put("IAB3-5","Construction-施工");
        CATS.put("IAB3-6","Forestry-林业");
        CATS.put("IAB3-7","Government-政府");
        CATS.put("IAB3-8","Green Solutions-绿色解决方案");
        CATS.put("IAB3-9","Human Resources-人力资源");
        CATS.put("IAB3-10","Logistics-后勤");
        CATS.put("IAB3-11","Marketing-营销");
        CATS.put("IAB3-12","Metals-金属");
        CATS.put("IAB4","Careers-招聘");
        CATS.put("IAB4-1","Career Planning-职业规划");
        CATS.put("IAB4-2","College-学院");
        CATS.put("IAB4-3","Financial Aid-经济资助");
        CATS.put("IAB4-4","Job Fairs-招聘会");
        CATS.put("IAB4-5","Job Search-求职");
        CATS.put("IAB4-6","Resume Writing/Advice-简历写作/建议");
        CATS.put("IAB4-7","Nursing-看护");
        CATS.put("IAB4-8","Scholarships-奖学金");
        CATS.put("IAB4-9","Telecommuting-远程办公");
        CATS.put("IAB4-10","U.S. Military-美军");
        CATS.put("IAB4-11","Career Advice-职业咨询");
        CATS.put("IAB5","Education-教育");
        CATS.put("IAB5-1","7-12 Education-7-12教育");
        CATS.put("IAB5-2","Adult Education-成人教育");
        CATS.put("IAB5-3","Art History-艺术史");
        CATS.put("IAB5-4","College Administration-学院行政");
        CATS.put("IAB5-5","College Life-大学生活");
        CATS.put("IAB5-6","Distance Learning-远程教育");
        CATS.put("IAB5-7","English as a 2nd Language-英语作为第二语言");
        CATS.put("IAB5-8","Language Learning-语言学习");
        CATS.put("IAB5-9","Graduate School-研究所");
        CATS.put("IAB5-10","Homeschooling-在家上学");
        CATS.put("IAB5-11","Homework/Study Tips-家庭作业/学习技巧");
        CATS.put("IAB5-12","K-6 Educators-K-6教育工作者");
        CATS.put("IAB5-13","Private School-私立学校");
        CATS.put("IAB5-14","Special Education-特殊教育");
        CATS.put("IAB5-15","Studying Business-学习商业");
        CATS.put("IAB6","Family & Parenting-家庭与育儿");
        CATS.put("IAB6-1","Adoption-采用");
        CATS.put("IAB6-2","Babies & Toddlers-婴儿和幼儿");
        CATS.put("IAB6-3","Daycare/Pre School-日托/幼儿园");
        CATS.put("IAB6-4","Family Internet-家庭互联网");
        CATS.put("IAB6-5","Parenting - K-6 Kids-育儿-K-6儿童");
        CATS.put("IAB6-6","Parenting teens-育儿青少年");
        CATS.put("IAB6-7","Pregnancy-怀孕");
        CATS.put("IAB6-8","Special Needs Kids-特殊需要的孩子");
        CATS.put("IAB6-9","Eldercare-老年护理");
        CATS.put("IAB7","Health & Fitness-健康与健身");
        CATS.put("IAB7-1","Exercise-行使");
        CATS.put("IAB7-2","ADD-加");
        CATS.put("IAB7-3","AIDS/HIV-艾滋病/HIV");
        CATS.put("IAB7-4","Allergies-过敏");
        CATS.put("IAB7-5","Alternative Medicine-替代药物");
        CATS.put("IAB7-6","Arthritis-关节炎");
        CATS.put("IAB7-7","Asthma-哮喘");
        CATS.put("IAB7-8","Autism/PDD-自闭症/PDD");
        CATS.put("IAB7-9","Bipolar Disorder-双相情感障碍");
        CATS.put("IAB7-10","Brain Tumor-脑肿瘤");
        CATS.put("IAB7-11","Cancer-癌症");
        CATS.put("IAB7-12","Cholesterol-胆固醇");
        CATS.put("IAB7-13","Chronic Fatigue Syndrome-慢性疲劳综合症");
        CATS.put("IAB7-14","Chronic Pain-慢性疼痛");
        CATS.put("IAB7-15","Cold & Flu-感冒和流感");
        CATS.put("IAB7-16","Deafness-聋");
        CATS.put("IAB7-17","Dental Care-牙齿保健");
        CATS.put("IAB7-18","Depression-萧条");
        CATS.put("IAB7-19","Dermatology-皮肤科");
        CATS.put("IAB7-20","Diabetes-糖尿病");
        CATS.put("IAB7-21","Epilepsy-癫痫");
        CATS.put("IAB7-22","GERD/Acid Reflux-GERD/酸回流");
        CATS.put("IAB7-23","Headaches/Migraines-头痛/偏头痛");
        CATS.put("IAB7-24","Heart Disease-心脏病");
        CATS.put("IAB7-25","Herbs for Health-健康草药");
        CATS.put("IAB7-26","Holistic Healing-整体治疗");
        CATS.put("IAB7-27","IBS/Crohn’s Disease-IBS/克罗恩病");
        CATS.put("IAB7-28","Incest/Abuse Support-乱伦/虐待支持");
        CATS.put("IAB7-29","Incontinence-失禁");
        CATS.put("IAB7-30","Infertility-不孕不育");
        CATS.put("IAB7-31","Men’s Health-男性健康");
        CATS.put("IAB7-32","Nutrition-营养");
        CATS.put("IAB7-33","Orthopedics-骨科");
        CATS.put("IAB7-34","Panic/Anxiety Disorders-恐慌/焦虑症");
        CATS.put("IAB7-35","Pediatrics-儿科");
        CATS.put("IAB7-36","Physical Therapy-物理疗法");
        CATS.put("IAB7-37","Psychology/Psychiatry-心理/精神科");
        CATS.put("IAB7-38","Senior Health-高级卫生");
        CATS.put("IAB7-39","Sexuality-性欲");
        CATS.put("IAB7-40","Sleep Disorders-睡眠障碍");
        CATS.put("IAB7-41","Smoking Cessation-戒烟");
        CATS.put("IAB7-42","Substance Abuse-物质滥用");
        CATS.put("IAB7-43","Thyroid Disease-甲状腺疾病");
        CATS.put("IAB7-44","Weight Loss-减肥");
        CATS.put("IAB7-45","Women's Health-女性健康");
        CATS.put("IAB8","Food & Drink-食物和饮料");
        CATS.put("IAB8-1","American Cuisine-美国菜");
        CATS.put("IAB8-2","Barbecues & Grilling-烧烤和烧烤");
        CATS.put("IAB8-3","Cajun/Creole-印第安/克里奥尔");
        CATS.put("IAB8-4","Chinese Cuisine-中国菜");
        CATS.put("IAB8-5","Cocktails/Beer-鸡尾酒/啤酒");
        CATS.put("IAB8-6","Coffee/Tea-咖啡/茶");
        CATS.put("IAB8-7","Cuisine-Specific-美食特定");
        CATS.put("IAB8-8","Desserts & Baking-甜点和烘焙");
        CATS.put("IAB8-9","Dining Out-外出就餐");
        CATS.put("IAB8-10","Food Allergies-食物过敏");
        CATS.put("IAB8-11","French Cuisine-法国美食");
        CATS.put("IAB8-12","Health/Low-Fat Cooking-健康/低脂烹饪");
        CATS.put("IAB8-13","Italian Cuisine-意大利美食");
        CATS.put("IAB8-14","Japanese Cuisine-日本料理");
        CATS.put("IAB8-15","Mexican Cuisine-墨西哥菜");
        CATS.put("IAB8-16","Vegan-素食主义者");
        CATS.put("IAB8-17","Vegetarian-素");
        CATS.put("IAB8-18","Wine-葡萄酒");
        CATS.put("IAB9","Hobbies & Interests-兴趣爱好");
        CATS.put("IAB9-1","Art/Technology-艺术/技术");
        CATS.put("IAB9-2","Arts & Crafts-工艺品");
        CATS.put("IAB9-3","Beadwork-串珠");
        CATS.put("IAB9-4","Bird-Watching-观鸟");
        CATS.put("IAB9-5","Board Games/Puzzles-棋盘游戏/拼图");
        CATS.put("IAB9-6","Candle & Soap Making-蜡烛和肥皂制作");
        CATS.put("IAB9-7","Card Games-纸牌游戏");
        CATS.put("IAB9-8","Chess-棋");
        CATS.put("IAB9-9","Cigars-雪茄");
        CATS.put("IAB9-10","Collecting-搜集");
        CATS.put("IAB9-11","Comic Books-漫画书");
        CATS.put("IAB9-12","Drawing/Sketching-绘图/素描");
        CATS.put("IAB9-13","Freelance Writing-自由写作");
        CATS.put("IAB9-14","Genealogy-家谱");
        CATS.put("IAB9-15","Getting Published-出版");
        CATS.put("IAB9-16","Guitar-吉他");
        CATS.put("IAB9-17","Home Recording-家庭录音");
        CATS.put("IAB9-18","Investors & Patents-投资者和专利");
        CATS.put("IAB9-19","Jewelry Making-珠宝制作");
        CATS.put("IAB9-20","Magic & Illusion-魔术与幻想");
        CATS.put("IAB9-21","Needlework-针线活");
        CATS.put("IAB9-22","Painting-绘画");
        CATS.put("IAB9-23","Photography-摄影");
        CATS.put("IAB9-24","Radio-无线电");
        CATS.put("IAB9-25","Roleplaying Games-角色扮演游戏");
        CATS.put("IAB9-26","Sci-Fi & Fantasy-科幻与幻想");
        CATS.put("IAB9-27","Scrapbooking-拼贴");
        CATS.put("IAB9-28","Screenwriting-编剧");
        CATS.put("IAB9-29","Stamps & Coins-邮票和硬币");
        CATS.put("IAB9-30","Video & Computer Games-视频和电脑游戏");
        CATS.put("IAB9-31","Woodworking-木工");
        CATS.put("IAB10","Home & Garden-家居与园艺");
        CATS.put("IAB10-1","Appliances-家电");
        CATS.put("IAB10-2","Entertaining-娱乐");
        CATS.put("IAB10-3","Environmental Safety-环境安全");
        CATS.put("IAB10-4","Gardening-园艺");
        CATS.put("IAB10-5","Home Repair-上门维修");
        CATS.put("IAB10-6","Home Theater-家庭电影院");
        CATS.put("IAB10-7","Interior Decorating-室内装饰");
        CATS.put("IAB10-8","Landscaping-园林绿化");
        CATS.put("IAB10-9","Remodeling & Construction-改造和建设");
        CATS.put("IAB11","Law, Government, & Politics-法律，政府和政治");
        CATS.put("IAB11-1","Immigration-移民");
        CATS.put("IAB11-2","Legal Issues-法律问题");
        CATS.put("IAB11-3","U.S. Government Resources-美国政府资源");
        CATS.put("IAB11-4","Politics-政治");
        CATS.put("IAB11-5","Commentary-评论");
        CATS.put("IAB12","News-新闻");
        CATS.put("IAB12-1","International News-国际新闻");
        CATS.put("IAB12-2","National News-国家新闻");
        CATS.put("IAB12-3","Local News-本地新闻");
        CATS.put("IAB13","Personal Finance-个人财务");
        CATS.put("IAB13-1","Beginning Investing-开始投资");
        CATS.put("IAB13-2","Credit/Debt & Loans-信用/债务和贷款");
        CATS.put("IAB13-3","Financial News-财经新闻");
        CATS.put("IAB13-4","Financial Planning-金融计划");
        CATS.put("IAB13-5","Hedge Fund-对冲基金");
        CATS.put("IAB13-6","Insurance-保险");
        CATS.put("IAB13-7","Investing-投资");
        CATS.put("IAB13-8","Mutual Funds-共同基金");
        CATS.put("IAB13-9","Options-选项");
        CATS.put("IAB13-10","Retirement Planning-退休计划");
        CATS.put("IAB13-11","Stocks-股票");
        CATS.put("IAB13-12","Tax Planning-税务筹划");
        CATS.put("IAB14","Society-社会");
        CATS.put("IAB14-1","Dating-约会");
        CATS.put("IAB14-2","Divorce Support-离婚支持");
        CATS.put("IAB14-3","Gay Life-同性恋生活");
        CATS.put("IAB14-4","Marriage-婚姻");
        CATS.put("IAB14-5","Senior Living-老年人生活");
        CATS.put("IAB14-6","Teens-青少年");
        CATS.put("IAB14-7","Weddings-婚礼");
        CATS.put("IAB14-8","Ethnic Specific-民族特色");
        CATS.put("IAB15","Science-科学");
        CATS.put("IAB15-1","Astrology-占星术");
        CATS.put("IAB15-2","Biology-生物学");
        CATS.put("IAB15-3","Chemistry-化学");
        CATS.put("IAB15-4","Geology-地质学");
        CATS.put("IAB15-5","Paranormal Phenomena-超自然现象");
        CATS.put("IAB15-6","Physics-物理");
        CATS.put("IAB15-7","Space/Astronomy-空间/天文学");
        CATS.put("IAB15-8","Geography-地理");
        CATS.put("IAB15-9","Botany-植物学");
        CATS.put("IAB15-10","Weather-天气");
        CATS.put("IAB16","Pets-宠物");
        CATS.put("IAB16-1","Aquariums-水族馆");
        CATS.put("IAB16-2","Birds-鸟类");
        CATS.put("IAB16-3","Cats-猫");
        CATS.put("IAB16-4","Dogs-小狗");
        CATS.put("IAB16-5","Large Animals-大型动物");
        CATS.put("IAB16-6","Reptiles-爬行动物");
        CATS.put("IAB16-7","Veterinary Medicine-老兵专用医药");
        CATS.put("IAB17","Sports-体育");
        CATS.put("IAB17-1","Auto Racing-赛车");
        CATS.put("IAB17-2","Baseball-棒球");
        CATS.put("IAB17-3","Bicycling-骑自行车");
        CATS.put("IAB17-4","Bodybuilding-健美运动");
        CATS.put("IAB17-5","Boxing-拳击");
        CATS.put("IAB17-6","Canoeing/Kayaking-独木舟/皮划艇");
        CATS.put("IAB17-7","Cheerleading-啦啦队");
        CATS.put("IAB17-8","Climbing-攀登");
        CATS.put("IAB17-9","Cricket-蟋蟀");
        CATS.put("IAB17-10","Figure Skating-花样滑冰");
        CATS.put("IAB17-11","Fly Fishing-钓飞鱼");
        CATS.put("IAB17-12","Football-足球");
        CATS.put("IAB17-13","Freshwater Fishing-淡水钓鱼");
        CATS.put("IAB17-14","Game & Fish-游戏和鱼");
        CATS.put("IAB17-15","Golf-高尔夫球");
        CATS.put("IAB17-16","Horse Racing-赛马");
        CATS.put("IAB17-17","Horses-马匹");
        CATS.put("IAB17-18","Hunting/Shooting-狩猎/射击");
        CATS.put("IAB17-19","Inline Skating-直排轮滑");
        CATS.put("IAB17-20","Martial Arts-武术");
        CATS.put("IAB17-21","Mountain Biking-山地骑行");
        CATS.put("IAB17-22","NASCAR Racing-NASCAR赛车");
        CATS.put("IAB17-23","Olympics-奥运会");
        CATS.put("IAB17-24","Paintball-彩弹");
        CATS.put("IAB17-25","Power & Motorcycles-电力和摩托车");
        CATS.put("IAB17-26","Pro Basketball-职业篮球");
        CATS.put("IAB17-27","Pro Ice Hockey-职业冰球");
        CATS.put("IAB17-28","Rodeo-圈地");
        CATS.put("IAB17-29","Rugby-橄榄球");
        CATS.put("IAB17-30","Running/Jogging-跑步/慢跑");
        CATS.put("IAB17-31","Sailing-帆船");
        CATS.put("IAB17-32","Saltwater Fishing-咸水钓鱼");
        CATS.put("IAB17-33","Scuba Diving-水肺潜水");
        CATS.put("IAB17-34","Skateboarding-滑板运动");
        CATS.put("IAB17-35","Skiing-滑雪");
        CATS.put("IAB17-36","Snowboarding-单板滑雪");
        CATS.put("IAB17-37","Surfing/Body-Boarding-冲浪/车身登机");
        CATS.put("IAB17-38","Swimming-游泳的");
        CATS.put("IAB17-39","Table Tennis/Ping-Pong-乒乓球/乒乓球");
        CATS.put("IAB17-40","Tennis-网球");
        CATS.put("IAB17-41","Volleyball-排球");
        CATS.put("IAB17-42","Walking-步行");
        CATS.put("IAB17-43","Waterski/Wakeboard-滑水/滑水");
        CATS.put("IAB17-44","World Soccer-世界足球");
        CATS.put("IAB18","Style & Fashion-风格与时尚");
        CATS.put("IAB18-1","Beauty-美女");
        CATS.put("IAB18-2","Body Art-人体艺术");
        CATS.put("IAB18-3","Fashion-时尚");
        CATS.put("IAB18-4","Jewelry-首饰");
        CATS.put("IAB18-5","Clothing-服装");
        CATS.put("IAB18-6","Accessories-饰品");
        CATS.put("IAB19","Technology & Computing-技术与计算");
        CATS.put("IAB19-1","3-D Graphics-三维图形");
        CATS.put("IAB19-2","Animation-动画");
        CATS.put("IAB19-3","Antivirus Software-防毒软件");
        CATS.put("IAB19-4","C/C++-C/C++");
        CATS.put("IAB19-5","Cameras & Camcorders-相机和摄像机");
        CATS.put("IAB19-6","Cell Phones-手机");
        CATS.put("IAB19-7","Computer Certification-计算机认证");
        CATS.put("IAB19-8","Computer Networking-计算机网络");
        CATS.put("IAB19-9","Computer Peripherals-电脑周边设备");
        CATS.put("IAB19-10","Computer Reviews-电脑评论");
        CATS.put("IAB19-11","Data Centers-数据中心");
        CATS.put("IAB19-12","Databases-数据库");
        CATS.put("IAB19-13","Desktop Publishing-桌面出版");
        CATS.put("IAB19-14","Desktop Video-桌面视频");
        CATS.put("IAB19-15","Email-电子邮件");
        CATS.put("IAB19-16","Graphics Software-图形软件");
        CATS.put("IAB19-17","Home Video/DVD-家庭视频/DVD");
        CATS.put("IAB19-18","Internet Technology-互联网技术");
        CATS.put("IAB19-19","Java-Java的");
        CATS.put("IAB19-20","JavaScript-JavaScript的");
        CATS.put("IAB19-21","Mac Support-Mac支持");
        CATS.put("IAB19-22","MP3/MIDI-MP3/MIDI");
        CATS.put("IAB19-23","Net Conferencing-网络会议");
        CATS.put("IAB19-24","Net for Beginners-网络初学者");
        CATS.put("IAB19-25","Network Security-网络安全");
        CATS.put("IAB19-26","Palmtops/PDAs-掌上电脑/掌上电脑");
        CATS.put("IAB19-27","PC Support-PC支持");
        CATS.put("IAB19-28","Portable-手提");
        CATS.put("IAB19-29","Entertainment-娱乐");
        CATS.put("IAB19-30","Shareware/Freeware-共享软件/免费软件");
        CATS.put("IAB19-31","Unix-Unix的");
        CATS.put("IAB19-32","Visual Basic-VisualBasic");
        CATS.put("IAB19-33","Web Clip Art-网络剪贴画");
        CATS.put("IAB19-34","Web Design/HTML-网页设计/HTML");
        CATS.put("IAB19-35","Web Search-网络搜索");
        CATS.put("IAB19-36","Windows-视窗");
        CATS.put("IAB20","Travel-旅行");
        CATS.put("IAB20-1","Adventure Travel-冒险旅行");
        CATS.put("IAB20-2","Africa-非洲");
        CATS.put("IAB20-3","Air Travel-航空旅行");
        CATS.put("IAB20-4","Australia & New Zealand-澳大利亚和新西兰");
        CATS.put("IAB20-5","Bed & Breakfasts-住宿加早餐");
        CATS.put("IAB20-6","Budget Travel-预算旅行");
        CATS.put("IAB20-7","Business Travel-商务旅行");
        CATS.put("IAB20-8","By US Locale-由美国本地人");
        CATS.put("IAB20-9","Camping-露营");
        CATS.put("IAB20-10","Canada-加拿大");
        CATS.put("IAB20-11","Caribbean-加勒比");
        CATS.put("IAB20-12","Cruises-游轮");
        CATS.put("IAB20-13","Eastern Europe-东欧洲");
        CATS.put("IAB20-14","Europe-欧洲");
        CATS.put("IAB20-15","France-法国");
        CATS.put("IAB20-16","Greece-希腊");
        CATS.put("IAB20-17","Honeymoons/Getaways-蜜月/自助游");
        CATS.put("IAB20-18","Hotels-酒店");
        CATS.put("IAB20-19","Italy-意大利");
        CATS.put("IAB20-20","Japan-日本");
        CATS.put("IAB20-21","Mexico & Central America-墨西哥和中美洲");
        CATS.put("IAB20-22","National Parks-国家公园");
        CATS.put("IAB20-23","South America-南美洲");
        CATS.put("IAB20-24","Spas-水疗");
        CATS.put("IAB20-25","Theme Parks-主题公园");
        CATS.put("IAB20-26","Traveling with Kids-和孩子一起旅行");
        CATS.put("IAB20-27","United Kingdom-英国");
        CATS.put("IAB21","Real Estate-房地产");
        CATS.put("IAB21-1","Apartments-公寓");
        CATS.put("IAB21-2","Architects-建筑师");
        CATS.put("IAB21-3","Buying/Selling Homes-购买/出售房屋");
        CATS.put("IAB22","Shopping-购物");
        CATS.put("IAB22-1","Contests & Freebies-比赛和免费赠品");
        CATS.put("IAB22-2","Couponing-优惠券");
        CATS.put("IAB22-3","Comparison-对照");
        CATS.put("IAB22-4","Engines-引擎");
        CATS.put("IAB23","Religion & Spirituality-宗教与灵性");
        CATS.put("IAB23-1","Alternative Religions-另类宗教");
        CATS.put("IAB23-2","Atheism/Agnosticism-无神论/不可知论");
        CATS.put("IAB23-3","Buddhism-佛教");
        CATS.put("IAB23-4","Catholicism-天主教");
        CATS.put("IAB23-5","Christianity-基督教");
        CATS.put("IAB23-6","Hinduism-印度教");
        CATS.put("IAB23-7","Islam-伊斯兰教");
        CATS.put("IAB23-8","Judaism-犹太教");
        CATS.put("IAB23-9","Latter-Day Saints-后期圣徒");
        CATS.put("IAB23-10","Pagan/Wiccan-异教/巫术");
        CATS.put("IAB24","Uncategorized-未分类");
        CATS.put("IAB25","Non-Standard Content-非标准内容");
        CATS.put("IAB25-1","Unmoderated UGC-未经调整的UGC");
        CATS.put("IAB25-2","Extreme Graphic/Explicit Violence-极端的图形/明确的暴力");
        CATS.put("IAB25-3","Pornography-色情");
        CATS.put("IAB25-4","Profane Content-亵渎内容");
        CATS.put("IAB25-5","Hate Content-仇恨内容");
        CATS.put("IAB25-6","Under Construction-正在施工");
        CATS.put("IAB25-7","Incentivized-诱因");
        CATS.put("IAB26","Illegal Content-非法内容");
        CATS.put("IAB26-1","Illegal Content-非法内容");
        CATS.put("IAB26-2","Warez-盗版软件");
        CATS.put("IAB26-3","Spyware/Malware-间谍软件/恶意软件");
        CATS.put("IAB26-4","Copyright Infringement-版权侵权");
    }

}
